import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "South Boston Masjid and Islamic Center",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                style={{
                    background: "#ECF4F4",
                }}
                className={inter.className}>
                {children}
            </body>
        </html>
    );
}
